# sites.example.yaml
crawl_targets:
  - data_name: "Sample Site 2"
    url: "https://example.com/path"
    table_selector: ""
    row_selector: ""
    filter_keyword: ""

  - data_name: "Sample Site 2"
    url: "https://another-example.org"
    table_selector: ""
    row_selector: ""
    filter_keyword: ""
